### ISSUE TITLE
You must install "@takuma-ru/vue-swipe-modal:^3.2.0"

### ISSUE THREAD

**Issue by takuma-ru** [Raon98/VueStudy#7]
Thank you for using `@takuma-ru/vue-swipe-modal`.

I have looked at your `package.json` and it seems that you are using `vue3.x`, so the version of the library you are installing is wrong.
Perhaps that is the reason it is not working properly.

Please correct `@takuma-ru/vue-swipe-modal` in your `package.json` and try installing again.

Wish you luck.

____
```md
@takuma-ru/vue-swipe-modal: "^3.2.0"
```

**Comment by Raon98** [comment]
takuma-ru
Thanks to you the problem has been solved
